
minimum-reputation: -120
maximum-reputation: 120
points-kill: -1
points-join: 4
dixpoint: 10
moindixpoint: -10

tablist:
  header: "§aBienvenue sur le serveur &6MonServeur"
  footer: "§6Amusez-vous bien sur notre serveur ! &aJoueurs en ligne : %players%"

reputation-status:
  honorable: "§dHonorable"
  good: "§aBonne"
  neutral: "§7Neutre"
  dangerous: "§6Dangereux"
  bad: "§cMauvaise"
  horrible: "§4Horrible"


reputation-prefix:
    honorable: "§dΩ"
    good: "§aΩ"
    neutral: "§7Ω"
    dangerous: "§6Ω"
    bad: "§cΩ"
    horrible: "§4Ω"




