
minimum-reputation: -120
maximum-reputation: 120
points-kill: -2
points-join: 4


tablist:
  header: "§aBienvenue sur le serveur &6MonServeur"
  footer: "§6Amusez-vous bien sur notre serveur ! &aJoueurs en ligne : %players%"

reputation-status:
  honorable: "§dHonorable"
  good: "§aBonne"
  neutral: "§7Neutre"
  dangerous: "§6Dangereux"
  bad: "§cMauvaise"
  horrible: "§4Horrible"

reputation-prefixe:
  honorable: "§dΩ Honorable§7"
  good: "§aΩ Bonne§7"
  neutral: "§7Ω Neutre§7"
  dangerous: "§6Ω Dangereux§7"
  bad: "§cΩ Mauvaise§7"
  horrible: "§4Ω Horrible§7"

reputation-prefix:
    honorable: "§dΩ"
    good: "§aΩ"
    neutral: "§7Ω"
    dangerous: "§6Ω"
    bad: "§cΩ"
    horrible: "§4Ω"




