
minimum-reputation: -120
maximum-reputation: 120
points-kill: -2
points-join: 4


tablist:
  header: "§aBienvenue sur le serveur &6Survie"
  footer: "§6Amusez-vous bien sur notre serveur ! &aJoueurs en ligne : {players}"


craft_limit: 50
craft_radius: 5

atm_amount: 100  # Argent gagné en cliquant sur le panneau
atm_message: "Vous avez retiré %amount% pièces depuis l'ATM !"


reputation-status:
  honorable: "§dHonorable"
  good: "§2Bonne"
  correct: "§acorrect"
  neutral: "§7Neutre"
  dangerous: "§6Dangereux"
  bad: "§cMauvaise"
  horrible: "§4Horrible"

reputation-prefixe:
  honorable: "§dΩ Honorable§7"
  good: "§2Ω Bonne§7"
  correct: "§aΩ correct§7"
  neutral: "§7Ω Neutre§7"
  dangerous: "§6Ω Dangereux§7"
  bad: "§cΩ Mauvaise§7"
  horrible: "§4Ω Horrible§7"

reputation-prefix:
    honorable: "§dΩ"
    good: "§2Ω"
    correct: "§aΩ"
    neutral: "§7Ω"
    dangerous: "§6Ω"
    bad: "§cΩ"
    horrible: "§4Ω"

    drop-chance: 50.0


addLoreOnCreative: true  # true pour activer, false pour désactiver l'ajout du lore

autoBanOnLowReputation: true  # true pour activer, false pour désactiver
reputationThreshold: -120     # La réputation à partir de laquelle un joueur sera banni
banDurationDays: 15

disable_thorns:
  enabled: true  # Désactive les enchantements Épine pour les joueurs, mais pas pour les mobs
  only_pvp: true  # Si activé, désactive uniquement pour les combats entre joueurs
  mobs_affected: false  # Laisser les mobs affectés par les Épine