name: WizardStoneCraft
version: '0.0.15.0-Alpha'
main: fr.WizardStoneCraft.WizardStoneCraft
api-version: 1.21

description: Plugin Principal de WizardStoneCraft
author: Metal54400 and MetalGames - studio
website: http://5.48.143.126:25565
softdepend:
  - EssentialsX
  - LuckPerms
  - PlaceholderAPI
  - Vault

commands:

  broadcast:
    description: Envoie un message global
    usage: /broadcast
    permission: wizardstonecraft.broadcast

  repreload:
    description: Recharge la configuration de la réputation
    usage: /repreload
    aliases: [reputationreload]
    permission: wizardstonecraft.repreload

  repadd:
    description: Ajouter des points de réputation à un joueur.
    usage: /repadd <player> <amount>
    aliases: [reputationadd]
    permission: wizardstonecraft.repadd


  reptop:
    description: Afficher le top 5 des réputations.
    usage: /reptop
    aliases: [reputationTop]


  rep:
    description: Afficher les informations de réputation d'un joueur.
    usage: /rep <player>
    aliases: [reputation]


  help:
    description: Affiche l'aide sur la réputation
    usage: /help
    aliases: [aide]
    permission: wizardstonecraft.help

  tabreload:
    description: Recharge la configuration du tablist
    usage: /tabreload
    permission: wizardstonecraft.tabreload

  rephighlight:
    description: Met en évidence la réputation d'un joueur.
    usage: /rephighlight <player>
    permission: wizardstonecraft.rephighlight

permissions:
  wizardstonecraft.menu:
    description: Permet d'accéder au menu de gestion de réputation.
    default: op

  wizardstonecraft.broadcast:
    description: Permet d'envoyer des messages globaux.
    default: op
