name: WizardStoneCraft
version: '0.0.7'
main: fr.WizardStoneCraft.WizardStoneCraft
api-version: [1.21], [1.12], [1.16],[1.15],[1.13], [1.13],[1.17],[1.18],[1.19],[1.8],[1.7],[1.9],[1.10]

description: Plugin Principale de WizardStoneCraft
author: Metal54400 and MetalGames - studio
website: http://5.48.143.126:25565
softdepend:
  - EssentialsX
  - Luckperms
  - PlaceHolderAPI

commands:
  home:
    description: Ouvre le menu de réputation
    usage: /home <homelist>
    permission: wizard.home

  sethome:
    description: creer un home
    usage: /sethome <homename>
    permission: wizard.sethome

  repmenu:
    description: Ouvre le menu de réputation
    usage: /repmenu
    permission: repmenu.use

  repreload:
    description: Ajouter des points de réputation à un joueur.
    usage: /repreload
    aliases: reputationreload

  repadd:
    description: Ajouter des points de réputation à un joueur.
    usage: /repadd <player> <amount>
    aliases: reputationadd
  repsubtract:
    description: Soustraire des points de réputation à un joueur.
    usage: /repsubtract <player> <amount>
  reptop:
    description: Afficher le top 5 des réputations.
    usage: /reptop
    aliases: reputationTop
  rep:
    description: Afficher les informations de réputation d'un joueur.
    usage: /rep <player>
    aliases: reputation

  rephelp:
    description: aide sur la reputation
    usage: /rephelp
    aliases: reputationhelp

  tabreload:
    description: Reload the tablist configuration
    usage: /tabreload

  rephighlight:
    description: Mettre en évidence la réputation d'un joueur.
    usage: /rephighlight <player>




permissions:
  reputation.menu:
    description: Permet d'accéder au menu de gestion de réputation.
    default: op
